Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,7 @@ jobs:
       uses: actions/checkout@v2
     
     - name: Validate PR Message
+      id: validate_message
       run: |
         message=$(git log -1 --pretty=format:%s $GITHUB_SHA)
         pattern="^Issue #[0-9]+: .+"
@@ -23,3 +24,9 @@ jobs:
           echo "PR message does not follow the pattern. Please use 'Issue #XXX: Your message.'"
           exit 1
         fi
+        
+    - name: Set Status Check
+      if: ${{ failure() }}
+      run: |
+        echo "The PR message validation failed."
+        exit 1
